[package]
name = "d2n"
version = "0.1.0"
authors = ["the Deno authors"]
edition = "2018"
license = "MIT"
repository = "https://github.com/dsherret/d2n"
description = "Deno to Node/canonical TypeScript transform."

[features]
default = ["tokio-loader"]
tokio-loader = ["tokio", "reqwest"]
serialization = ["serde"]

[dependencies]
anyhow = "1.0.44"
base64 = "0.13.0"
deno_ast = { version = "0.2.0", features = ["bundler", "codegen", "dep_graph", "module_specifier", "proposal", "react", "sourcemap", "transforms", "typescript", "view", "visit", "utils"], path = "../../deno_ast" }
deno_graph = { version = "0.5.0", features = [], path = "../../deno_graph" }
futures = "0.3.17"
lazy_static = "1.4.0"
pathdiff = "0.2.0"
regex = "1.5"
reqwest = { version = "0.11", features = ["rustls"], optional = true }
serde = { version = "1.0.130", features = ["derive"], optional = true }
tokio = { version = "1", features = ["full"], optional = true }

[dev-dependencies]
pretty_assertions = "1.0.0"
